import { test, expect } from '@playwright/test';

test('Homepage', async ({ page }) => {

    // this test was generated by codegen
  await page.goto('https://demo.evershop.io/');

  // nav bar

  //verify the nav bar elements are visible

  // Shop dropdown menu
  await expect(page.getByRole('button', { name: 'Shop', exact: true })).toBeVisible(); // exact: true is used to match the button with the exact name "Shop"

  // About us link
  await expect(page.getByRole('link', { name: 'About us' })).toBeVisible();

    // EverShop logo link
  await expect(page.getByRole('link').nth(1)).toBeVisible();

    // Search input
  await expect(page.getByRole('link').nth(2)).toBeVisible();

    // Account link
  await expect(page.getByRole('link').nth(3)).toBeVisible();

    // Shopping cart button
  await expect(page.getByRole('button', { name: 'Shopping cart with 0 items' })).toBeVisible();

    // verify the main banner elements are visible
  await expect(page.locator('.slick-slide.slick-active > div > .relative.lg\\:h-auto > .relative > .absolute')).toBeVisible();

    // verify the main banner text and buttons are visible

    // verify the main banner text are visible
  await expect(page.getByRole('main')).toContainText('Crafted With Care');
  await expect(page.getByRole('main')).toContainText('Elegant designs that enhance your daily life, from morning coffee to home organization');
  await expect(page.getByRole('main')).toContainText('Premium Quality Products');
  await expect(page.getByRole('main')).toContainText('Discover our exquisite collection of ceramic and stainless steel products');


    // verify the main banner buttons are visible
  await expect(page.getByRole('link', { name: 'Shop Now' })).toBeVisible();
  await page.getByRole('button', { name: 'Next slide' }).click();
  await expect(page.getByRole('link', { name: 'View Collection' })).toBeVisible();

    // very that the arrow buttons for the hero banner are visible
  await expect(page.getByRole('button', { name: 'Previous slide' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Next slide' })).toBeVisible();

    // verify the sections below the hero banner are visible

    // verify Kids shoes collection section
  await expect(page.getByRole('main')).toContainText('Kids shoes collection');  // verify the text in the kids shoes collection 
  await expect(page.getByRole('main')).toContainText('Constructed from luxury nylons, leathers, and custom hardware, featuring sport details such as hidden breathing vents, waterproof + antimicrobial linings, and more.');
  await expect(page.getByRole('link', { name: 'Shop kids' })).toBeVisible();

    // verify Women shoes collection section
  await expect(page.getByRole('main')).toContainText('Women shoes collection');
  await expect(page.getByRole('main')).toContainText('Constructed from luxury nylons, leathers, and custom hardware, featuring sport details such as hidden breathing vents, waterproof + antimicrobial linings, and more.');
  await expect(page.getByRole('link', { name: 'Shop women' })).toBeVisible();

    // verify Men shoes collection section
  await expect(page.getByRole('main')).toContainText('Men shoes collection');
  await expect(page.getByRole('main')).toContainText('Constructed from luxury nylons, leathers, and custom hardware, featuring sport details such as hidden breathing vents, waterproof + antimicrobial linings, and more.');
  await expect(page.getByRole('link', { name: 'Shop men' })).toBeVisible();

    // verify the featured products section is visible
  await expect(page.getByRole('main')).toContainText('Featured Products');

    // verify the featured products are visible
  await expect(page.getByRole('main')).toMatchAriaSnapshot(`- heading "Featured Products" [level=3]`);
  await expect(page.getByRole('link', { name: 'Stainless Steel Thermos - Yellow Stainless Steel Thermos - Yellow $' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Stainless Steel Thermos - Black Stainless Steel Thermos - Black $' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Modern Ceramic Vase - Green' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Modern Ceramic Vase - Black' })).toBeVisible();

    // verify the footer elements are visible
  await expect(page.locator('div > .h-10 > path:nth-child(2)').first()).toBeVisible();
  await expect(page.locator('div').filter({ hasText: 'PayPal' }).nth(5)).toBeVisible();
  await expect(page.locator('div:nth-child(3) > .h-10 > path:nth-child(3)')).toBeVisible();

    // verify copyright text is visible
  await expect(page.getByText('© 2022 Evershop. All Rights')).toBeVisible();
});



  // verify that the "About us" link in the nav bar navigates to the correct page
test('link navigates to the correct about us page', async ({ page }) => {
  await page.goto('https://demo.evershop.io/');

  // 1. Click the link
  await page.getByRole('link', { name: 'About us' }).click();

  // 2. Assert the URL is exactly what you expect
  await expect(page).toHaveURL('https://demo.evershop.io/page/about-us');

  // 3. Optional: Assert a heading exists on the new page to be 100% sure
  await expect(page.getByRole('heading', { name: 'About Us' })).toBeVisible({ timeout: 15000 });
});




// verify that Accesories link in the Shop dropdown menu navigates to the correct page
test('verify Accessories link navigates to the correct page', async ({ page }) => {
  await page.goto('https://demo.evershop.io/');

   // Click the Shop dropdown menu
  await page.getByRole('button', { name: 'Shop', exact: true }).click();

   // select the Accessories link from the dropdown menu
  await page.getByRole('link', { name: 'Accessories' }).click();

    // Assert the URL is exactly what you expect
    await expect(page).toHaveURL('https://demo.evershop.io/accessories');

  // Assert a heading exists on the new page to be 100% sure
  await expect(page.getByRole('heading', { name: 'Accessories' })).toBeVisible({ timeout: 15000 });
});



  // verify that clicking on the search icon in the nav bar opens the search form input
test('verify search icon opens search form input', async ({ page }) => {

   // Homepage
  await page.goto('https://demo.evershop.io/');

    // click the search icon in the nav bar
  await page.getByRole('link').nth(2).click();

   // Assert visibility of the search input field
  await expect(page.locator('.form__field')).toBeVisible();
});

//verify account link in the nav bar navigates to the login page
test('verify account link navigates to the login page', async ({ page }) => {

  await page.goto('https://demo.evershop.io/');

   // click the account link in the nav bar
  await page.getByRole('link').nth(3).click();

    // Assert the URL is exactly what you expect
  await expect(page).toHaveURL('https://demo.evershop.io/account/login');
});



// verify that the shopping cart button opens the cart dialog and displays the correct message when the cart is empty
test('verify shopping cart button opens cart dialog', async ({ page }) => {

  await page.goto('https://demo.evershop.io/');
  
   // click the shopping cart button in the nav bar
  await page.getByRole('button', { name: 'Shopping cart with 0 items' }).click();

   // Assert the cart dialog is visible
  await expect(page.getByRole('dialog', { name: 'Your Cart' })).toBeVisible();
  
   // Assert the correct message is displayed when the cart is empty
  await expect(page.getByText('Your cart is empty')).toBeVisible();

   // Assert the "Continue Shopping" button is visible
  await expect(page.getByRole('button', { name: 'Continue Shopping' })).toBeVisible();
});



  // verify that clicking on the "Shop Now" button in the main banner navigates to the correct page
test('verify that clicking on the "Shop Now" button in the main banner navigates to the correct page', async ({ page }) => {

  await page.goto('https://demo.evershop.io/');

    // click the "Shop Now" button in the main banner

  await page.getByRole('link', { name: 'Shop Now' }).click();

    // Assert the URL is exactly what you expect
  await expect(page).toHaveURL('https://demo.evershop.io/accessories');

    // Assert a heading exists on the new page to be 100% sure
  await expect(page.getByRole('heading', { name: 'Accessories' })).toBeVisible({ timeout: 15000 });
});


  // verify that clicking on the "View Collection" button in the main banner navigates to the correct page
test('verify that clicking on the "View Collection" button in the main banner navigates to the correct page', async ({ page }) => {

  await page.goto('https://demo.evershop.io/');

    // click the "Next slide" button to navigate to the second slide in the main banner
  await page.getByRole('button', { name: 'Next slide' }).click();

    // click the "View Collection" button in the main banner
  await page.getByRole('link', { name: 'View Collection' }).click();

    // Assert the URL is exactly what you expect
  await expect(page).toHaveURL('https://demo.evershop.io/accessories');

    // Assert a heading exists on the new page to be 100% sure
  await expect(page.getByRole('heading', { name: '  Accessories' })).toBeVisible({ timeout: 15000 });
});


// verify that the "Shop kids" link in the Kids shoes collection section navigates to the correct page
test('verify that the "Shop kids" link in the Kids shoes collection section navigates to the correct page', async ({ page }) => {
  
  await page.goto('https://demo.evershop.io/');

    // click the "Shop kids" link in the Kids shoes collection section
  await page.getByRole('link', { name: 'Shop kids' }).click();  

    // Assert the URL is exactly what you expect
  await expect(page).toHaveURL('https://demo.evershop.io/kids');
});


  // verify that  the "Shop women" link in the Women shoes collection section navigates to the correct page
test('verify that  the "Shop women" link in the Women shoes collection section navigates to the correct page', async ({ page }) => {

  await page.goto('https://demo.evershop.io/');

    // click the "Shop  women" link in the Women shoes collection section
  await page.getByRole('link', { name: 'Shop women' }).click();

    // Assert the URL is exactly what you expect
  await expect(page).toHaveURL('https://demo.evershop.io/women');
});


  // verify that the "Shop  men" link in the    Men shoes collection section navigates to the correct page
test('verify that the "Shop men" link in the Men shoes collection section navigates to the correct page', async ({ page }) => {

  await page.goto('https://demo.evershop.io/')

    // click the "Shop men" link in the Men shoes collection section
  await page.getByRole('link', { name: 'Shop men' }).click();

    // Assert the URL is exactly what you expect
  await expect(page).toHaveURL('https://demo.evershop.io/men');
});



 // verify that clicking on a featured product navigates to the correct product page
test('verify that clicking on a featured product navigates to the correct product page', async ({ page }) => {

  await page.goto('https://demo.evershop.io/');

    // click on the first featured product which is the "Stainless Steel Thermos - Yellow"
  await page.getByRole('link', { name: 'Stainless Steel Thermos - Yellow Stainless Steel Thermos - Yellow $' }).click();

    // Assert the URL is exactly what you expect
  await expect(page).toHaveURL('https://demo.evershop.io/accessories/stainless-steel-thermos-yellow');

    // Assert the product name is visible on the product page to be 100% sure we are on the correct page
  await expect(page.getByRole('heading', { name: 'Stainless Steel Thermos - Yellow' })).toBeVisible({ timeout: 15000 });
});







 // verify that account creation is unsuccessful when registered user email is entered in the registration form
test('verify that account creation is unsuccessful when a registered user email is entered in the registration form', async ({ page })  => {

  await page.goto('https://demo.evershop.io/');

    // click the account link in the nav bar to navigate to the login page
  await page.getByRole('link').nth(3).click();

    // click the "Create an account" link to navigate to the registration page
  await page.getByRole('link', { name: 'Create an account' }).click();

  await page.waitForLoadState('domcontentloaded')

    // fill out the registration form with valid information
  await page.getByRole('textbox', { name: 'Full Name *' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('Joseph Ogunsuada');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('josephogunsuada@gmail.com');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('ogunsuada');

   // click the "Sign Up" button to submit the registration form
  await page.getByRole('button', { name: 'Sign Up' }).click();

  await page.waitForLoadState('domcontentloaded')
  
    // Assert that the error message "Email is already used" is visible
  await page.waitForSelector('text=Email is already used', { timeout: 15000 });
await expect(page.getByText('Email is already used')).toBeVisible();
});



// verify login is unsuccessful when  incorrect password is entered for a registered user email
test('verify login is unsuccessful when incorrect password is entered for a registered user email', async ({ page }) => {

  await page.goto('https://demo.evershop.io/');

    // click the account link in the nav bar to navigate to the login page
  await page.getByRole('link').nth(3).click();

  await page.waitForLoadState('domcontentloaded')

    // fill out the login form with a registered user email and incorrect password
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('josephogunsuada@gmail.com');

  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('incorrectpassword');

   // click the "Login" button to submit the login form
  await page.getByRole('button', { name: 'Sign In' }).click();

  

    // Assert that the error message "Invalid email or password" is visible
  await page.waitForSelector('text=Invalid email or password', { timeout: 15000 });
  await expect(page.getByText('Invalid email or password')).toBeVisible();
});



 // verify that a registered user can successfully log in with correct credentials
test('verify that a registered user can successfully log in with correct credentials', async ({ page }) => {  

  await page.goto('https://demo.evershop.io/');

    // click the account link in the nav bar to navigate to the login page
  await page.getByRole('link').nth(3).click();

  await page.waitForLoadState('domcontentloaded')
    // fill out the login form with a registered user email and correct password
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('jostemi70@gmail.com');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('Anuoluwa70@');

    // click the "Login" button to submit the login form
  await page.getByRole('button', { name: 'Sign In' }).click();

  await page.waitForLoadState('domcontentloaded')

    // Assert that the URL is exactly what you expect after successful login
  await expect(page).toHaveURL('https://demo.evershop.io/' , { timeout: 15000 });
});

  //End of test cases for the EverShop demo website.







  //E2E TESTING SCENARIO: Verify that a user can successfully add a product to the cart and proceed to checkout
test('verify that a user can successfully add a product to the cart and proceed to checkout', async ({ page }) => { 
  
    // Navigate to the homepage
  await page.goto('https://demo.evershop.io/');

    // Click on the first featured product which is the "Stainless Steel Thermos - Yellow"
  await page.getByRole('link', { name: 'Stainless Steel Thermos - Yellow Stainless Steel Thermos - Yellow $' }).click();

    //Select an available color option for the product
    await page.goto('https://demo.evershop.io/accessories/stainless-steel-thermos-yellow?color=3', { waitUntil: 'domcontentloaded' });

    // Click the "Add to Cart" button on the product page
  await page.getByRole('button', { name: 'ADD TO CART' }).click();  

    // Assert that the cart dialog is visible 
  await expect(page.getByRole('heading', { name: 'Your Cart' })).toBeVisible();

    // Click the "Checkout" button in the cart dialog
  await page.getByRole('button', { name: 'Checkout' }).click(); 

    // Assert that the URL is exactly what you expect for the checkout page
  await expect(page).toHaveURL('https://demo.evershop.io/checkout');
});




// Assert Product page contains correct product information
test('Assert Product page contains correct product information', async ({ page }) => {

  // Navigate to the product page for "Stainless Steel Thermos - Yellow"
  await page.goto('https://demo.evershop.io/accessories/stainless-steel-thermos-yellow?color=3', { waitUntil: 'domcontentloaded' });
  
    // Assert there is price text with the correct value
  await expect(page.getByText('$')).toBeVisible();

    // Assert that the product image is visible
  await expect(page.getByRole('img', { name: 'Stainless Steel Thermos -' })).toBeVisible();

    // Assert that the product name is visible on the product page
  await expect(page.getByRole('heading', { name: 'Stainless Steel Thermos -' })).toBeVisible();

   // Assert that the product color selcted is visible
  await expect(page.getByText('Color: Yellow')).toBeVisible();

    // Assert that the product SKU is visible
  await expect(page.getByText('SKU: THERMO-005-YEL')).toBeVisible();

    // Assert that the color variation is visible
  await expect(page.getByText('ColorBlackYellow')).toBeVisible();

    // Assert that the color variant options are visible
  await expect(page.getByRole('button', { name: 'Yellow' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Black' })).toBeVisible();

    // Assert that the quantity selector is visible
  await expect(page.getByRole('group').filter({ hasText: /^Quantity\*$/ })).toBeVisible();

    // Assert that the "Add to Cart" button is visible
  await expect(page.getByRole('button', { name: 'ADD TO CART' })).toBeVisible();

    // Assert that the product description section is visible
  await expect(page.locator('.column__container')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Product Description' })).toBeVisible();
});

//E2E TESTING SCENARIO: Verify that a user can successfully log out from their account
test('verify that a user can successfully log out from their account', async ({ page }) => {  
  await page.goto('https://demo.evershop.io/');

    // click the account link in the nav bar to navigate to the login page
  await page.getByRole('link').nth(3).click();    
  await page.waitForLoadState('domcontentloaded')
    
    // fill out the login form with a registered user email and correct password
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('jostemi70@gmail.com');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('Anuoluwa70@');

    // click the "Login" button to submit the login form
  await page.getByRole('button', { name: 'Sign In' }).click();  

    // Assert that the URL is exactly what you expect after successful login
  await expect(page).toHaveURL('https://demo.evershop.io/' , { timeout: 15000 });

    // Click the account link in the nav bar to open the account dropdown menu
  await page.getByRole('link').nth(3).click();    
  await page.waitForLoadState('domcontentloaded')

    // Click the "Logout" link in the account dropdown menu
  await page.getByRole('link', { name: 'Logout' }).click(); 

    // Assert that the URL is exactly what you expect after logout
  await expect(page).toHaveURL('https://demo.evershop.io/');
});




// E2E TESTING SCENARIO: Verify that the search functionality returns relevant results when a user searches for a product
test('verify that the search functionality returns relevant results when a user searches for a product', async ({ page }) => {
  await page.goto('https://demo.evershop.io/');
  
    // click the search icon in the nav bar to open the search input field
  await page.getByRole('link').nth(2).click();

    // fill out the search input field with a product name
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('Stainless Steel Thermos - Yellow');   

    // Assert that the search results page is displayed with relevant results
  await expect(page.getByRole('button', { name: 'Stainless Steel Thermos - Yellow' })).toBeVisible();
}); 



//E2E testing from login to checkout process
test.skip('E2E testing from login to checkout process', async ({ page }) => {
  await page.goto('https://demo.evershop.io/'); 

    // click the account link in the nav bar to navigate to the login page
  await page.getByRole('link').nth(3).click();    
  await page.waitForLoadState('domcontentloaded')

    // fill out the login form with a registered user email and correct password  
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('jostemi70@gmail.com');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('Anuoluwa70@');

    // click the "Login" button to submit the login form
  await page.getByRole('button', { name: 'Sign In' }).click();  

    // Assert that the URL is exactly what you expect after successful login
  await expect(page).toHaveURL('https://demo.evershop.io/' , { timeout: 15000 });

    // click on Shop dropdown menu in the nav bar
  await page.getByRole('button', { name: 'Shop', exact: true }).click();

    // select the Accessories link from the dropdown menu
  await page.getByRole('link', { name: 'Accessories' }).click();

    // Assert the URL is exactly what you expect
  await expect(page).toHaveURL('https://demo.evershop.io/accessories');

    // click on the first product in the Accessories category which is the "Stainless Steel Thermos - Yellow"
  await page.getByRole('link', { name: 'Stainless Steel Thermos - Yellow Stainless Steel Thermos - Yellow $' }).click();

    //Select an available color option for the product
  await page.goto('https://demo.evershop.io/accessories/stainless-steel-thermos-yellow?color=3', { waitUntil: 'domcontentloaded' });

    // Click the "Add to Cart" button on the product page
  await page.getByRole('button', { name: 'ADD TO CART' }).click();

    // Assert that the cart dialog is visible 
  await expect(page.getByRole('heading', { name: 'Your Cart' })).toBeVisible(); 

    // Click the "Check out" button in the cart dialog
  await page.getByRole('button', { name: 'Checkout' }).click();

    // Assert that the URL is exactly what you expect for the checkout page
  await expect(page).toHaveURL('https://demo.evershop.io/checkout');  

   // Assert that the checkout page contains the correct product information
  //await expect(page.getByRole('heading', { name: 'Checkout' })).toBeVisible();
  //await expect(page.getByRole('link', { name: 'Stainless Steel Thermos - Yellow' })).toBeVisible();
  //await expect(page.getByText('$')).toBeVisible();


  await page.waitForLoadState('domcontentloaded')

  await expect(page.getByText('Shipping Address', { exact: true })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Full name *' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Telephone *' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Address *' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Address 2' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'City *' })).toBeVisible();
  await expect(page.getByRole('combobox', { name: 'Country *' })).toBeVisible();
  await expect(page.getByRole('combobox', { name: 'Province *' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Postcode *' })).toBeVisible();

   // Assert that shipping method section is visible
  await expect(page.getByText('Shipping Method', { exact: true })).toBeVisible();

    // Assert that the billing information section is visible
  await expect(page.locator('div').filter({ hasText: /^Same as shipping address$/ }).first()).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Use a different billing address$/ }).first()).toBeVisible();

   // Assert that the payment method section is visible
  await expect(page.getByText('Pick a payment method')).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Cash On Delivery$/ }).first()).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Paypal$/ }).first()).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Credit Card$/ }).first()).toBeVisible();

  // Fill out the shipping information form
  await page.getByRole('textbox', { name: 'Full name *' }).click();
  await page.getByRole('textbox', { name: 'Full name *' }).fill('Joseph Ogunsuada');
  await page.getByRole('textbox', { name: 'Telephone *' }).click();
  await page.getByRole('textbox', { name: 'Telephone *' }).fill('09018150913');
  await page.getByRole('textbox', { name: 'Address *' }).click();
  await page.getByRole('textbox', { name: 'Address *' }).fill('123 Main St');
  await page.getByRole('textbox', { name: 'Address 2' }).click();
  await page.getByRole('textbox', { name: 'Address 2' }).fill('Apt 4B');
  await page.getByRole('textbox', { name: 'City *' }).click();
  await page.getByRole('textbox', { name: 'City *' }).fill('New York');
  await page.getByRole('combobox', { name: 'Country *' }).click();
  await page.getByRole('option', { name: 'United States' }).click();
  await page.getByRole('combobox', { name: 'Province *' }).click();
  await page.getByRole('option', { name: 'New York' }).click();
  await page.getByRole('textbox', { name: 'Postcode *' }).click();
  await page.getByRole('textbox', { name: 'Postcode *' }).fill('10001');


  // Wait for the shipping methods to load before selecting a shipping method
  

  

  // Select a shipping method
  await page.getByText('Express$').click();
  //await page.waitForLoadState('networkidle');
  // Click the span with role=radio that's in the Basic row
  await page.locator('span[role="radio"][data-slot="radio-group-item"][tabindex="0"]').nth(0).click({force : true });
  await page.waitForLoadState('networkidle');


  // Select a payment method
  await page.waitForLoadState('networkidle');
  await page.getByText('Cash On Delivery').click();

  // Click the "Place Order" button to submit the order
  await page.getByRole('button', { name: 'Place Order' }).click();

  await page.waitForLoadState('domcontentloaded')

  // Assert that the URL is exactly what you expect for the order confirmation page
 await expect(page).toHaveURL(/demo\.evershop\.io\/checkout\/success\/.+/);


  // Assert that the order confirmation page is displayed with the correct information
  await expect(page.getByText('Thank you Joseph Seven!')).toBeVisible({ timeout: 15000 });

  // Click the "Continue Shopping" button on the order confirmation page
  await page.getByRole('button', { name: 'CONTINUE SHOPPING' }).click();

  // Assert that the URL is exactly what you expect after clicking "Continue Shopping"
  await expect(page).toHaveURL('https://demo.evershop.io/');

});

// END OF E2E TESTING SCENARIO